"""
Seed script to populate the database with real Indian government schemes
Run: python seed.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from app.db.database import SessionLocal, engine
from app.models.models import Base, Category, Scheme

Base.metadata.create_all(bind=engine)

db = SessionLocal()

# Create categories
categories = [
    {"name": "Agriculture & Farmers", "slug": "farmers", "description": "Schemes for farmers and agricultural workers"},
    {"name": "Housing", "slug": "housing", "description": "Housing and shelter schemes"},
    {"name": "Education & Scholarships", "slug": "education", "description": "Scholarship and education schemes"},
    {"name": "Women & Children", "slug": "women", "description": "Empowerment schemes for women and children"},
    {"name": "Health & Insurance", "slug": "health", "description": "Health and medical insurance schemes"},
    {"name": "Employment & Skill", "slug": "employment", "description": "Employment and skill development programs"},
    {"name": "Senior Citizens", "slug": "senior", "description": "Schemes for senior citizens and elderly"},
    {"name": "Disabled Persons", "slug": "disability", "description": "Schemes for persons with disabilities"},
    {"name": "Financial Inclusion", "slug": "finance", "description": "Banking, savings and financial inclusion schemes"},
    {"name": "Business & MSME", "slug": "business", "description": "Schemes for entrepreneurs and small businesses"},
]

cat_objs = {}
for cat in categories:
    existing = db.query(Category).filter(Category.slug == cat["slug"]).first()
    if not existing:
        obj = Category(**cat)
        db.add(obj)
        db.flush()
        cat_objs[cat["slug"]] = obj
    else:
        cat_objs[cat["slug"]] = existing

# Seed schemes
schemes = [
    {
        "scheme_name": "PM Kisan Samman Nidhi",
        "description": "Financial support to farmer families with income support of ₹6000 per year in three equal installments of ₹2000 each.",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["farmers"].id,
        "benefits": "₹6,000 per year (₹2,000 every 4 months) direct bank transfer",
        "documents_required": ["Aadhaar Card", "Bank Account Details", "Land Records", "Mobile Number"],
        "apply_link": "https://pmkisan.gov.in/",
        "official_website": "https://pmkisan.gov.in/",
        "target_occupation": "farmer",
        "income_limit": 200000,
    },
    {
        "scheme_name": "PM Fasal Bima Yojana",
        "description": "Pradhan Mantri Fasal Bima Yojana provides crop insurance to farmers against crop loss due to natural calamities.",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["farmers"].id,
        "benefits": "Crop loss compensation up to 90% of insured sum",
        "documents_required": ["Aadhaar Card", "Land Records", "Bank Account", "Crop Sowing Certificate"],
        "apply_link": "https://pmfby.gov.in/",
        "official_website": "https://pmfby.gov.in/",
        "target_occupation": "farmer",
    },
    {
        "scheme_name": "Kisan Credit Card",
        "description": "Kisan Credit Card scheme provides farmers with affordable short-term credit to meet their agricultural needs.",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["farmers"].id,
        "benefits": "Short-term credit up to ₹3 lakh at 7% interest (4% with subsidy)",
        "documents_required": ["Aadhaar Card", "Land Records", "Bank Account", "Passport Photo"],
        "apply_link": "https://www.pmkisan.gov.in/",
        "target_occupation": "farmer",
    },
    {
        "scheme_name": "Pradhan Mantri Awas Yojana (Gramin)",
        "description": "PM Awas Yojana provides financial assistance to homeless and kutcha house owners to construct a pucca house.",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["housing"].id,
        "benefits": "₹1.20 lakh (plain areas) / ₹1.30 lakh (hilly areas) for house construction",
        "documents_required": ["Aadhaar Card", "BPL Certificate", "Bank Account", "Caste Certificate (if applicable)"],
        "apply_link": "https://pmayg.nic.in/",
        "official_website": "https://pmayg.nic.in/",
        "income_limit": 300000,
    },
    {
        "scheme_name": "Pradhan Mantri Awas Yojana (Urban)",
        "description": "Credit Linked Subsidy Scheme for home loans in urban areas for economically weaker sections.",
        "ministry": "Ministry of Housing and Urban Affairs",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["housing"].id,
        "benefits": "Home loan interest subsidy of 3%–6.5% (up to ₹2.67 lakh)",
        "documents_required": ["Aadhaar Card", "Income Proof", "Property Documents", "Bank Account"],
        "apply_link": "https://pmaymis.gov.in/",
        "official_website": "https://pmaymis.gov.in/",
        "income_limit": 1800000,
    },
    {
        "scheme_name": "Ayushman Bharat – PM Jan Arogya Yojana",
        "description": "World's largest health insurance scheme providing ₹5 lakh health coverage per family per year for secondary and tertiary care hospitalisation.",
        "ministry": "Ministry of Health and Family Welfare",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["health"].id,
        "benefits": "Health coverage up to ₹5 lakh per family per year",
        "documents_required": ["Aadhaar Card", "Ration Card", "SECC Data Verification"],
        "apply_link": "https://pmjay.gov.in/",
        "official_website": "https://pmjay.gov.in/",
        "income_limit": 200000,
    },
    {
        "scheme_name": "National Scholarship Portal – Merit cum Means",
        "description": "Scholarships for students from minority communities based on merit and financial needs.",
        "ministry": "Ministry of Minority Affairs",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["education"].id,
        "benefits": "Up to ₹20,000 per year (post-matric) or ₹1,000 per month maintenance allowance",
        "documents_required": ["Aadhaar Card", "Income Certificate", "Marksheets", "Bank Account", "Caste/Minority Certificate"],
        "apply_link": "https://scholarships.gov.in/",
        "official_website": "https://scholarships.gov.in/",
        "income_limit": 250000,
        "target_category": "Minority",
    },
    {
        "scheme_name": "SC/ST Post Matric Scholarship",
        "description": "Scholarships for SC and ST students studying at post-matric or post-secondary stage.",
        "ministry": "Ministry of Social Justice and Empowerment",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["education"].id,
        "benefits": "Course fees + maintenance allowance up to ₹1,200 per month",
        "documents_required": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Marksheet", "Bank Account"],
        "apply_link": "https://scholarships.gov.in/",
        "income_limit": 250000,
        "target_category": "SC/ST",
    },
    {
        "scheme_name": "Sukanya Samriddhi Yojana",
        "description": "A government savings scheme for the welfare of girl children offering attractive interest rate and tax benefits.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["women"].id,
        "benefits": "8.2% interest rate, tax exemption on deposit, maturity amount and withdrawal",
        "documents_required": ["Girl Child's Birth Certificate", "Parent's Aadhaar", "Address Proof"],
        "apply_link": "https://www.indiapost.gov.in/",
        "target_gender": "female",
        "max_age": 10,
    },
    {
        "scheme_name": "Beti Bachao Beti Padhao",
        "description": "Scheme to prevent gender biased sex selective elimination, ensure survival and protection of girl child.",
        "ministry": "Ministry of Women and Child Development",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["women"].id,
        "benefits": "Financial assistance for girl child education and welfare programs",
        "documents_required": ["Birth Certificate", "Aadhaar Card", "Income Certificate"],
        "apply_link": "https://wcd.nic.in/bbbp-schemes",
        "target_gender": "female",
    },
    {
        "scheme_name": "PM Mudra Yojana",
        "description": "Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["business"].id,
        "benefits": "Shishu: up to ₹50,000 | Kishore: ₹50,000 to ₹5 lakh | Tarun: ₹5 lakh to ₹10 lakh (collateral-free)",
        "documents_required": ["Aadhaar Card", "PAN Card", "Business Plan", "Bank Statements", "Address Proof"],
        "apply_link": "https://www.mudra.org.in/",
    },
    {
        "scheme_name": "PM Suraksha Bima Yojana",
        "description": "Accident insurance scheme offering ₹2 lakh coverage for accidental death at just ₹20/year premium.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["health"].id,
        "benefits": "₹2 lakh accidental death/disability cover at ₹20/year premium",
        "documents_required": ["Aadhaar Card", "Bank Account (auto-debit)"],
        "apply_link": "https://financialservices.gov.in/",
        "min_age": 18,
        "max_age": 70,
        "income_limit": 500000,
    },
    {
        "scheme_name": "Atal Pension Yojana",
        "description": "Guaranteed pension scheme for workers in unorganised sector providing ₹1,000–₹5,000 monthly pension.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["senior"].id,
        "benefits": "Monthly pension of ₹1,000–₹5,000 after age 60",
        "documents_required": ["Aadhaar Card", "Bank Account", "Mobile Number"],
        "apply_link": "https://npscra.nsdl.co.in/",
        "min_age": 18,
        "max_age": 40,
    },
    {
        "scheme_name": "PM Jeevan Jyoti Bima Yojana",
        "description": "Life insurance scheme providing ₹2 lakh life cover at just ₹436/year.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["health"].id,
        "benefits": "₹2 lakh life insurance cover at just ₹436/year",
        "documents_required": ["Aadhaar Card", "Bank Account (auto-debit)", "Nominee Details"],
        "apply_link": "https://financialservices.gov.in/",
        "min_age": 18,
        "max_age": 50,
    },
    {
        "scheme_name": "PM Jan Dhan Yojana",
        "description": "Financial inclusion program providing zero-balance savings accounts with RuPay debit card and ₹2 lakh insurance.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["finance"].id,
        "benefits": "Zero-balance account, RuPay card, ₹2 lakh accident cover, ₹10,000 overdraft",
        "documents_required": ["Aadhaar Card", "Passport Photo"],
        "apply_link": "https://pmjdy.gov.in/",
    },
    {
        "scheme_name": "MGNREGS – Mahatma Gandhi NREGA",
        "description": "Provides 100 days guaranteed wage employment per year to rural households.",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["employment"].id,
        "benefits": "100 days guaranteed employment at ₹200–₹300/day (state-specific)",
        "documents_required": ["Aadhaar Card", "Job Card", "Bank Account"],
        "apply_link": "https://nrega.nic.in/",
        "income_limit": 200000,
    },
    {
        "scheme_name": "PM Skill Development Yojana (PMKVY)",
        "description": "Skill training and certification program for Indian youth to enhance employability.",
        "ministry": "Ministry of Skill Development and Entrepreneurship",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["employment"].id,
        "benefits": "Free skill training + ₹8,000 reward on certification + job placement assistance",
        "documents_required": ["Aadhaar Card", "Class 10 Certificate", "Bank Account"],
        "apply_link": "https://www.pmkvyofficial.org/",
        "min_age": 15,
        "max_age": 45,
    },
    {
        "scheme_name": "National Old Age Pension Scheme (NOAPS)",
        "description": "Monthly pension to destitute senior citizens above 60 years.",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["senior"].id,
        "benefits": "₹200–₹500 per month pension (state top-up available)",
        "documents_required": ["Aadhaar Card", "Age Proof", "Income Certificate", "BPL Card"],
        "apply_link": "https://nsap.nic.in/",
        "min_age": 60,
        "income_limit": 100000,
    },
    {
        "scheme_name": "Divyangjan Scholarship",
        "description": "Scholarship for students with disabilities to continue post-matric education.",
        "ministry": "Ministry of Social Justice and Empowerment",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["disability"].id,
        "benefits": "Tuition fee + maintenance allowance up to ₹1,200 per month",
        "documents_required": ["Aadhaar Card", "Disability Certificate (≥40%)", "Income Certificate", "Marksheet"],
        "apply_link": "https://scholarships.gov.in/",
        "income_limit": 250000,
        "target_category": "Divyang",
    },
    {
        "scheme_name": "Stand Up India",
        "description": "Facilitates bank loans between ₹10 lakh and ₹1 crore to SC/ST and women borrowers for setting up greenfield enterprises.",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "applicable_state": "all",
        "category_id": cat_objs["business"].id,
        "benefits": "Loans from ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs",
        "documents_required": ["Aadhaar Card", "PAN Card", "Business Plan", "Caste/Gender Certificate", "Bank Statements"],
        "apply_link": "https://www.standupmitra.in/",
        "target_category": "SC/ST",
    },
    {
        "scheme_name": "Mukhyamantri Kanya Sumangala Yojana",
        "description": "Financial assistance to families with girl children in Uttar Pradesh to ensure their education and health.",
        "ministry": "UP State Government",
        "scheme_type": "state",
        "applicable_state": "Uttar Pradesh",
        "category_id": cat_objs["women"].id,
        "benefits": "₹15,000 provided in 6 installments from birth to graduation",
        "documents_required": ["Aadhaar", "Domicile Certificate", "Birth Certificate", "Bank Account"],
        "apply_link": "https://mksy.up.gov.in/",
        "target_gender": "female",
    },
    {
        "scheme_name": "Maharashtra Mahatma Jyotirao Phule Jan Arogya Yojana",
        "description": "Health insurance scheme by Maharashtra government providing cashless medical facilities.",
        "ministry": "Maharashtra State Government",
        "scheme_type": "state",
        "applicable_state": "Maharashtra",
        "category_id": cat_objs["health"].id,
        "benefits": "Cashless medical treatment up to ₹1.5 lakh per family per year",
        "documents_required": ["Ration Card", "Aadhaar Card", "Domicile Certificate"],
        "apply_link": "https://www.jeevandayee.gov.in/",
    },
    {
        "scheme_name": "Ladli Behna Yojana",
        "description": "Monthly financial assistance to women born in Madhya Pradesh to empower them financially and improve social status.",
        "ministry": "MP State Government",
        "scheme_type": "state",
        "applicable_state": "Madhya Pradesh",
        "category_id": cat_objs["women"].id,
        "benefits": "₹1,250 direct cash transfer every month",
        "documents_required": ["Aadhaar Card", "Samagra ID", "Bank Account (DBT linked)"],
        "apply_link": "https://cmladlibahna.mp.gov.in/",
        "target_gender": "female",
        "min_age": 21,
        "max_age": 60,
    }
]

for scheme_data in schemes:
    existing = db.query(Scheme).filter(Scheme.scheme_name == scheme_data["scheme_name"]).first()
    if not existing:
        obj = Scheme(**scheme_data)
        db.add(obj)

db.commit()
db.close()
print(f"✅ Seeded {len(categories)} categories and {len(schemes)} schemes successfully!")
